apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: quay.io/cytan/quarkus-podname:latest
  newName: quay.io/mpua/quarkus-podname
  newTag: f0d0008b4fe93c262fb5a59abd417b6dae62ce43
